'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GatewayRestart
    Public Property GatewayRestartId As System.Guid
    Public Property CreatedOn As Nullable(Of Date)
    Public Property SpeedUp As Nullable(Of Decimal)
    Public Property SpeedDown As Nullable(Of Decimal)
    Public Property Ipv4Address As String

End Class
