'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WanSpeed
    Public Property WanSpeedId As System.Guid
    Public Property SpeedUp As Decimal
    Public Property SpeedDown As Decimal
    Public Property SpeedTime As Date
    Public Property Ipv4Address As String

End Class
